### ISSUE TITLE
Error on Chapter 6 practice problems, page 169

### ISSUE THREAD

**Issue by charlielu05** [mikexcohen/LinAlgBook#9]
Hi Mike, thanks for creating this fantastic book. I've tried many different linear algebra text books by various authors (Gilbert Strang included) but this one was the only one that gave me that "a-ha" moment. 

Anyways, thought I'd like to point out that the error on page 169, practice problem **a** where it asks to calculate the Euclidean distance between the following pairs of matrices.
The answer in the book is `sqrt(322)` but I think the correct answer should be `sqrt(306)`.

![image](https://github.com/mikexcohen/LinAlgBook/assets/25814936/fc8eef9d-910c-47ce-b622-8f543b680726)

**Comment by charlielu05** [comment]
Realised I made a typo in matrix B!

**Comment by mikexcohen** [comment]
Hi charlielu05. Thank you for your kind words. I'm glad you found the issue (and I'm glad it wasn't an error in the book :P ). Anyway, the concepts are more important than the arithmetic, and you clearly understood the concept regardless of the sign of the "2".
